flaskStatic/app/__init__.py
from typing import Type
from flask import Flask
from config import config

def create_app(app_config: str = 'development') -> Type[Flask]:
  app: Type[Flask] = Flask(__name__) 
  app.config.from_object(config[app_config])

  from app.main.routes import main

  app.register_blueprint(main)
  
  return app

flaskStatic/app/main/routes.py
from flask import Blueprint, render_template
from typing import Type, Text
from app.products.products import product


main: Type[Blueprint] = Blueprint('main', __name__)

@main.route('/', methods = ['GET'])
def index() -> Text:
  return render_template('index.html', products=product['all_products'])

@main.route('/show/<int:product_id>', methods =['GET'])
def show(product_id: int) -> Text:
  find_prouct_by_id = lambda x: x['product_id'] == product_id
  products = product['all_products']
  item = list(filter(find_prouct_by_id, products))
  return render_template('show.html', item=item)

flaskStatic/app/templates/index.html
{% extends 'layout.html' %}

{% block content %}
  {% for product in products %}
  <div class="wrapper">
    <div class='container'>
      <h1 id='product-name'>{{ product['product_name']}}</h1>
        <a href={{ url_for('main.show', product_id = product['product_id']) }}>
          <div class="image-container">
            <img class='product-image' src={{ url_for('static', filename=product['product_image'])}} alt={{ product['product_image'] }}>
          </div>
        </a>
    </div>
  </div>
  {% endfor %}
{% endblock content %}

flaskStatic/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href={{ url_for('static', filename='css/styles.css') }}>
  <title>Document</title>
</head>
<body>
  {% block content %} {% endblock content %}
</body>
</html>

flaskStatic/app/templates/show.html
{% extends 'layout.html' %}

{% block content %}
  <span>
    <a href={{ url_for('main.index') }}>Home</a>
  </span>
  <div>
    {% for items in item %}
      <h1>{{ items['product_name'] }}</h1>
      <div class='show-image'>
        <img src={{ url_for('static', filename= items['product_image']) }} alt={{ items['product_image'] }}>
      </div>
    {% endfor %}
    <a href="">
      <span>Buy product</span>
    </a>
  </div>
{% endblock content %}